### PR TITLE
Fix compilation with recent OpenFL versions

### PR DESCRIPTION
**Pull request by jgranick**
This fixes compile issues I had testing HaxeUI with the current OpenFL release :smile:

### CODE REVIEW

**Comment by ianharrigan** [comment]
oh really? And thats it? This isnt haxeui2 btw...

**Comment by ianharrigan** [comment]
Still thats amazing, thanks loads - i guess that would mean haxeui v1 isnt linked openfl legacy anymore then??

**Comment by jgranick** [comment]
I tried HelloWorld, I suppose I could try more samples, but that was all to get things booting and running on Windows

**Comment by ianharrigan** [comment]
I see, it thought it was more involved than that for some reason. Maybe i was being blind / dumb / both. Either way, thats pretty great - thanks. 

One thing, how come v1? V2 is here: https://github.com/haxeui/haxeui-core

I presume this might just be because of the issue on the openfl forums?

**Pull request merged**
