### PR TITLE
//

### PR DESCRIPTION
**Pull request by Justinfront**
Was looking through my repositories and it says still able to merge so presume this is not yet corrected?

### CODE REVIEW

**Comment by ianharrigan** [comment]
Totally forgot about this if im honest. Let me check...

**Comment by ianharrigan** [comment]
I think my only issue (not sure if you agree) is that on html5 targets the properly should be there, but just not "work", ie:

Instead of:

```haxe
#if html5
public function get_z():Float {
    return _sprite.z
}
#end
```

It should be more like:

```haxe
public function get_z():Float {
    #if html5
    return _sprite.z
    #end
}
```
So the property still exists, but doesnt cause a problem. Again, not sure if you agree with this?

**Comment by Justinfront** [comment]
Is it cleaner for it not to exist so that the user does not try to use it on Javascript, and any code requiring z will give a suitable error for js target, to have it silently not do anything will just confuse a user, better to only add it back later when it has a function, remember html is pretty slow without unused code. But either way is good.

Also the rebuildLocalLib.hxml is very useful inclusion I find it saves me a lot of time on my projects, but probably needs a pc and mac version.

**Comment by ianharrigan** [comment]
Fair enough, youve convinced me... Probably better to fail rather than expect it to work and be confused when it doesnt.

**Comment by ianharrigan** [comment]
for me personally, i use the batch file (on windows)... "haxeui build", "haxeui install", "haxeui submit"... But doesnt hurt to have the hxml file... I probably wont use it, but doesnt mean no one else will... 

Thanks for the update/addition!

Cheers,
Ian

**Pull request merged**
