### PR TITLE
Temporary roots

### PR DESCRIPTION
**Pull request by Kloda**
In the game I’m working on I would like to show modal popups at a place where there’s no underlying gui to attach it to. I thought it would be nice if PopupManager could create a temporary root in those cases.

By passing the stage to config.root a root will be created with the stage as parent and then be destroyed when the popup is disposed.

### CODE REVIEW

**Comment by ianharrigan** [comment]
I think the PR is fine (and probably quite useful)... However, im probably going to change the code style after i merge... Im a stickler for consistent code style... :/

Hope you dont mind!

Cheers,
Ian

**Comment by Kloda** [comment]
Great, no prob!

**Comment by ianharrigan** [comment]
Quick question, any chance you could provide me with a code snippet that makes use of this feature? Im wondering if it might be able to be extended a little so it doesnt just apply to popups? Need to think about it, but might be a way to get around root creation altogether (possibily).

Cheers,
Ian

**Comment by Kloda** [comment]
You just call one of the show methods like so:

PopupManager.instance.showSimple("Message", null, { root: Lib.current.stage, buttons: PopupButton.OK });

**Comment by Kloda** [comment]
Another possibility could be to have a static root created in Toolkit.init() reserved for this purpose.

Also I think it would make sense to do this for all popups by default. It would ensure that they always are centered on the screen and always visible, regardless of the size and position of the "current root" and regardless of whether that root is currently visible or not.

**Pull request closed without merging**
